# Generated by Django 5.0.6 on 2024-05-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.AlterField(
            model_name='user',
            name='email_activation_code',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='کد فعال سازی حساب'),
        ),
    ]
