# Generated by Django 5.0.6 on 2024-05-17 09:14

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0005_alter_productcomment_options_alter_product_liked_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='نام خانوادگی')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='تلفن')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد پستی')),
                ('address', models.TextField(blank=True, max_length=700, null=True, verbose_name='آدرس')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده')),
                ('payment_data', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='زمان پرداخت')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سبد خرید',
                'verbose_name_plural': 'سبدهای خرید',
                'ordering': ('is_paid', '-payment_data'),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('paid_price', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='قیمت پرداخت شده')),
                ('discount', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='تخفیف')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='سفارش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.productcolorvariant', verbose_name='نوع رنگی محصول')),
            ],
            options={
                'verbose_name': 'محصول سبد خرید',
                'verbose_name_plural': 'محصولات سبد خرید',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['is_paid', '-payment_data'], name='orders_orde_is_paid_2eb632_idx'),
        ),
    ]
