# Generated by Django 5.0.6 on 2024-05-17 09:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('is_paid', '-payment_date'), 'verbose_name': 'سبد خرید', 'verbose_name_plural': 'سبدهای خرید'},
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_is_paid_2eb632_idx',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='payment_data',
            new_name='payment_date',
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['is_paid', '-payment_date'], name='orders_orde_is_paid_209c00_idx'),
        ),
    ]
