# Generated by Django 5.0.6 on 2024-05-10 22:42

import colorfield.fields
import django.core.validators
import django.db.models.deletion
import django_jalali.db.models
import products.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=300, verbose_name='نام رنگ')),
                ('color_hex_code', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=[('#000000', 'سیاه'), ('#FFFFFF', 'سفید'), ('#FF0000', 'قرمز'), ('#0000FF', 'آبی'), ('#008000', 'سبز'), ('#FFFF00', 'زرد'), ('#FFA500', 'نارنجی'), ('#800080', 'بنفش'), ('#FFC0CB', 'صورتی'), ('#964B00', 'قهوه ای'), ('#808080', 'طوسی')], verbose_name='کد hex رنگ')),
            ],
            options={
                'verbose_name': 'رنگ محصول',
                'verbose_name_plural': 'رنگ های محصول',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to='images/categories/', verbose_name='تصویر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=products.deletion.SET_PARENT, related_name='subsets', to='products.category', verbose_name='والد')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='حذف شده')),
                ('deleted_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True, verbose_name='حذف شده در تاریخ')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='اسلاگ')),
                ('short_description', models.CharField(max_length=350, verbose_name='توضیحات کوتاه')),
                ('long_description', models.TextField(verbose_name='توضیحات کامل')),
                ('specification', models.JSONField(blank=True, default=dict, null=True, verbose_name='مشخصات فنی')),
                ('weight', models.PositiveIntegerField(verbose_name='وزن')),
                ('price', models.PositiveBigIntegerField(verbose_name='قیمت')),
                ('discount', models.PositiveIntegerField(verbose_name='تخفیف')),
                ('main_image', models.ImageField(upload_to='images/products/', verbose_name='تصویر اصلی')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='بروز\u200cرسانی شده در')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('liked_by', models.ManyToManyField(blank=True, related_name='liked_products', to='accounts.visitor', verbose_name='پسندیده شده توسط')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=products.deletion.SET_PARENT, related_name='products', to='products.category', verbose_name='دسته بندی والد')),
                ('visitors', models.ManyToManyField(blank=True, related_name='visited_products', to='accounts.visitor', verbose_name='بازدید کننده ها')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DeletedProduct',
            fields=[
            ],
            options={
                'verbose_name': 'محصول حذف شده',
                'verbose_name_plural': 'محصولات حذف شده',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='ProductColorVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='حذف شده')),
                ('deleted_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True, verbose_name='حذف شده در تاریخ')),
                ('price', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='قیمت')),
                ('discount', models.PositiveIntegerField(blank=True, null=True, verbose_name='تخفیف')),
                ('stock_count', models.PositiveIntegerField(verbose_name='تعداد موجودی')),
                ('color', models.ForeignKey(on_delete=products.deletion.SOFT_CASCADE, related_name='product_color_variants', to='products.color', verbose_name='رنگ')),
                ('product', models.ForeignKey(on_delete=products.deletion.SOFT_CASCADE, related_name='product_color_variants', to='products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'نوع رنگی محصول',
                'verbose_name_plural': 'نوع های رنگی محصولات',
            },
        ),
        migrations.AddField(
            model_name='color',
            name='products',
            field=models.ManyToManyField(related_name='color_variants', through='products.ProductColorVariant', to='products.product', verbose_name='رنگ ها'),
        ),
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='پیام')),
                ('rate', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='نمره')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='products.productcomment', verbose_name='والد')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='products.product', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نظر محصول',
                'verbose_name_plural': 'نظرات محصول',
            },
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/products/', verbose_name='تصویر')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'گالری محصول',
                'verbose_name_plural': 'گالری های محصول',
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['id', 'slug'], name='products_pr_id_a08e3c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created_at', '-updated_at'], name='products_pr_created_266fdd_idx'),
        ),
        migrations.AddIndex(
            model_name='productcomment',
            index=models.Index(fields=['-created_at'], name='products_pr_created_9f5611_idx'),
        ),
    ]
