# Generated by Django 5.0.6 on 2024-05-13 09:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.PositiveIntegerField(blank=True, verbose_name='تخفیف'),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='rate',
            field=models.PositiveSmallIntegerField(blank=True, default=5, null=True, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='نمره'),
        ),
    ]
