# Generated by Django 5.0.6 on 2024-05-13 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_discount_alter_productcomment_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'product': models.F('product')}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='products.productcomment', verbose_name='والد'),
        ),
    ]
