# Generated by Django 5.0.6 on 2024-05-16 20:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productcomment_parent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcomment',
            options={'ordering': ['-created_at'], 'verbose_name': 'نظر محصول', 'verbose_name_plural': 'نظرات محصول'},
        ),
        migrations.AlterField(
            model_name='product',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_products', to=settings.AUTH_USER_MODEL, verbose_name='پسندیده شده توسط'),
        ),
    ]
